git config --global credential.helper store
git config --global pull.rebase true
git config --global merge.conflictstyle zdiff3
git config --global rerere.enabled true
git config --global diff.algorithm histogram
git config --global branch.sort -committerdate
git config --global core.autocrlf false
git config --global core.editor code
git config --global fetch.prune true
git config --global log.date iso